# Generated by Django 2.1.2 on 2019-01-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_Name', models.CharField(max_length=50, verbose_name='First Name')),
                ('first_Name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_Birth', models.DateTimeField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.AddField(
            model_name='junior',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person'),
        ),
    ]
