# Generated by Django 2.1.2 on 2019-01-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190115_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='junior',
            name='actual_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weigh In Weight'),
        ),
        migrations.AddField(
            model_name='junior',
            name='age_group',
            field=models.CharField(choices=[('6-8', '6-8'), ('9-10', '9-10'), ('11-12', '11-12'), ('13-15', '13-15'), ('16-18', '16-18')], max_length=10, null=True, verbose_name='Age Group'),
        ),
        migrations.AddField(
            model_name='junior',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='us_citizen',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
