# Generated by Django 2.1.2 on 2019-01-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190117_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='judo_card',
            field=models.CharField(choices=[('USJUDO', 'USA Judo'), ('USJA', 'USJA'), ('USJF', 'USJF')], max_length=6, null=True),
        ),
    ]
