# Generated by Django 2.1.2 on 2019-01-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20190117_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='junior',
            name='up_one_age',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='Second Division Weight'),
        ),
        migrations.AddField(
            model_name='junior',
            name='up_one_weight',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='Second Division Age'),
        ),
    ]
