# Generated by Django 2.1.2 on 2019-01-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20190117_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
