# Generated by Django 2.1.5 on 2019-02-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20190131_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='Has Paid'),
        ),
    ]
