# Generated by Django 2.1.5 on 2019-02-17 22:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_person_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='waiver',
            field=models.BooleanField(default=False, verbose_name='Has Signed Waiver'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_Name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_Name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Please use the format: <em>+12223334444</em>.', max_length=128, null=True, verbose_name='Tel. #'),
        ),
    ]
