# Generated by Django 2.1.5 on 2019-02-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20190217_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='proposedweightclass',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Proposed Weight Class (kgs)'),
        ),
        migrations.AlterField(
            model_name='junior',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight (kgs)'),
        ),
    ]
