# Generated by Django 2.1.5 on 2019-02-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20190224_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('6-8', '2011-2012 (6-8)'), ('9-10', '2009-2010 (9-10)'), ('11-12', '2007-2008 (11-12)'), ('13-14', '2005-2006 (13-14)'), ('15-17', '2002-2004 (15-17)'), ('18-20', '1999-2001 (18-20)')], max_length=10, null=True, verbose_name='Age Group')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight (kgs)')),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weigh In Weight')),
                ('up_one_age', models.BooleanField(default=False, max_length=1, verbose_name='Second Division Weight')),
                ('up_one_weight', models.BooleanField(default=False, max_length=1, verbose_name='Second Division Age')),
            ],
        ),
        migrations.RemoveField(
            model_name='junior',
            name='person',
        ),
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(blank=True, choices=[('1Jr', 'One Youth Division ($70)'), ('2Jr_Wt', '2 Youth Divisions - Up One Weight ($105)'), ('2Jr_Age', '2 Youth Divisions - Up One Age ($105)'), ('1Jr_1Nv', '1 Youth + 1 Senior Non-Elite ($105)'), ('1Jr_1Sr', '1 Youth + 1 Senior Elite Division ($125)'), ('1Nv', '1 Non-Elite Senior Division ($70)'), ('2Nv', '2 Non-Elite Senior Divisions ($105)'), ('1Nv_1Vt', '1 Novice and 1 Veteran ($105)'), ('1Nv_1Sr', '1 Non-Elite + 1 Elite Senior Division ($125)'), ('1Sr', '1 Senior Elite Division ($90)'), ('2Sr', '2 Senior Elite Divisions ($150)'), ('1Vt', '1 Veteran Division ($70)'), ('1Vt_1Nv', '1 Veteran and 1 Senior Non-Elite Division ($125)'), ('1Vt_1Sr', '1 Veteran and 1 Senior Elite Division ($125)')], max_length=10, null=True, verbose_name='Divisions'),
        ),
        migrations.AlterField(
            model_name='person',
            name='proposedweightclass',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Estimated weigh-in weight (e.g., 57)', max_digits=4, null=True, verbose_name='Proposed Weight Class (kgs)'),
        ),
        migrations.DeleteModel(
            name='Junior',
        ),
        migrations.AddField(
            model_name='juniormale',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person'),
        ),
    ]
