# Generated by Django 2.1.5 on 2019-02-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20190226_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorFemale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('6-8', '2011-2012 (6-8)'), ('9-10', '2009-2010 (9-10)'), ('11-12', '2007-2008 (11-12)'), ('13-14', '2005-2006 (13-14)'), ('15-17', '2002-2004 (15-17)'), ('18-20', '1999-2001 (18-20)')], max_length=10, null=True, verbose_name='Age Group')),
                ('weight_class', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight Class (kgs)')),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weigh In Weight')),
                ('up_one_age', models.BooleanField(default=False, max_length=1, verbose_name='Second Division Weight')),
                ('up_one_weight', models.BooleanField(default=False, max_length=1, verbose_name='Second Division Age')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='juniormale',
            name='weight',
        ),
        migrations.AddField(
            model_name='juniormale',
            name='weight_class',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight Class (kgs)'),
        ),
    ]
