# Generated by Django 2.1.5 on 2019-03-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20190226_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorFemale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight (kgs)')),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weigh In Weight (kgs)')),
            ],
            options={
                'verbose_name': 'Senior Female',
            },
        ),
        migrations.CreateModel(
            name='SeniorMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight (kgs)')),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weigh In Weight (kgs)')),
            ],
            options={
                'verbose_name': 'Senior Male',
            },
        ),
        migrations.RemoveField(
            model_name='senior_advanced',
            name='person',
        ),
        migrations.RemoveField(
            model_name='senior_novice',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='veteran',
            options={'verbose_name': 'Veteran'},
        ),
        migrations.AlterField(
            model_name='person',
            name='judo_card',
            field=models.CharField(blank=True, choices=[('USJUDO', 'USA Judo'), ('USJA', 'USJA'), ('USJF', 'USJF'), ('INTL', 'International')], max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='Senior_Advanced',
        ),
        migrations.DeleteModel(
            name='Senior_Novice',
        ),
        migrations.AddField(
            model_name='seniormale',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person'),
        ),
        migrations.AddField(
            model_name='seniorfemale',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person'),
        ),
    ]
