# Generated by Django 2.1.5 on 2019-04-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20190302_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorfemale',
            name='category',
            field=models.CharField(blank=True, choices=[('Novice', 'Novice'), ('Elite', 'Elite')], max_length=6, null=True, verbose_name='Competitor Category'),
        ),
        migrations.AddField(
            model_name='seniormale',
            name='category',
            field=models.CharField(blank=True, choices=[('Novice', 'Novice'), ('Elite', 'Elite'), ('Brown', 'Brown')], max_length=6, null=True, verbose_name='Competitor Category'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State'),
        ),
    ]
