# Generated by Django 2.1.5 on 2019-04-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20190407_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteran',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='Gender'),
        ),
    ]
