# Generated by Django 2.1.5 on 2019-04-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_veteran_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorfemale',
            name='up_one_category',
            field=models.BooleanField(default=False, max_length=1, verbose_name='Second Division Novice/Elite'),
        ),
        migrations.AddField(
            model_name='seniorfemale',
            name='up_one_weight',
            field=models.BooleanField(default=False, max_length=1, verbose_name='Second Division Weight'),
        ),
        migrations.AddField(
            model_name='seniormale',
            name='up_one_category',
            field=models.BooleanField(default=False, max_length=1, verbose_name='Second Division Novice/Elite'),
        ),
        migrations.AddField(
            model_name='seniormale',
            name='up_one_weight',
            field=models.BooleanField(default=False, max_length=1, verbose_name='Second Division Weight'),
        ),
        migrations.AlterField(
            model_name='juniorfemale',
            name='up_one_age',
            field=models.BooleanField(default=False, max_length=1, verbose_name='Second Division Age'),
        ),
        migrations.AlterField(
            model_name='juniorfemale',
            name='up_one_weight',
            field=models.BooleanField(default=False, max_length=1, verbose_name='Second Division Weight'),
        ),
    ]
