# Generated by Django 2.1.5 on 2019-04-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20190409_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoviceFemale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight (kgs)')),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weigh In Weight (kgs)')),
                ('up_one_weight', models.BooleanField(default=False, max_length=1, verbose_name='Second Division Weight')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person')),
            ],
            options={
                'verbose_name': 'Novice Female',
            },
        ),
        migrations.AlterModelOptions(
            name='seniorfemale',
            options={'verbose_name': 'Elite Female'},
        ),
        migrations.RemoveField(
            model_name='seniorfemale',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seniorfemale',
            name='up_one_category',
        ),
        migrations.AlterField(
            model_name='veteran',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True, verbose_name='Gender'),
        ),
    ]
