# Generated by Django 2.1.5 on 2019-04-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_auto_20190420_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoviceMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Novice', 'Novice'), ('Brown', 'Brown')], max_length=6, null=True, verbose_name='Competitor Category')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight (kgs)')),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weigh In Weight (kgs)')),
                ('up_one_category', models.BooleanField(default=False, max_length=1, verbose_name='Second Division Novice/Elite')),
                ('up_one_weight', models.BooleanField(default=False, max_length=1, verbose_name='Second Division Weight')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Person')),
            ],
            options={
                'verbose_name': 'Senior Male',
            },
        ),
        migrations.AlterModelOptions(
            name='seniormale',
            options={'verbose_name': 'Elite Male'},
        ),
        migrations.RemoveField(
            model_name='seniormale',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seniormale',
            name='up_one_category',
        ),
    ]
