# Generated by Django 2.1.5 on 2019-04-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20190420_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novicemale',
            options={'verbose_name': 'Novice Male'},
        ),
    ]
